--This script inserts data into the domain tables

-- Insert data into the dom_observer table
-- Observers have been anonymized
BEGIN;
INSERT INTO domains.dom_observer (sort_order, data_value, label)
VALUES
(1,'obs01','Observer 1'),
(2,'obs02','Observer 2'),
(3,'obs03','Observer 3'),
(4,'obs04','Observer 4'),
(5,'obs05','Observer 5'),
(6,'obs06','Observer 6'),
(7,'obs07','Observer 7'),
(8,'obs08','Observer 8'),
(9,'obs09','Observer 9'),
(10,'obs10','Observer 10'),
(11,'obs11','Observer 11'),
(12,'obs12','Observer 12'),
(13,'obs13','Observer 13'),
(14,'obs14','Observer 14');
--COMMIT;

-- Insert data into the dom_physiography table
--BEGIN;
INSERT INTO domains.dom_physiography (sort_order, data_value, label, definition)
VALUES
(1,'a','Alpine','Alpine physiography encompasses high-elevation mountain terrain that is dominated by tundra vegetation and barrens. This class excludes glaciers and recently deglaciated (i.e.; since approx. 1950) areas in the high mountains that are considered glaciated physiography.'),
(2,'l','Lowland','Lowland physiography includes areas below treeline that are flat; concave; or gently sloping. Areas of lowland physiography typically occur lower in elevation than adjacent uplands. Soil moisture status ranges from wet to permanently flooded.'),
(3,'p','Lacustrine','Lacustrine physiography encompasses areas of the landscape adjacent to lakes and ponds that are affected by the lake or pond hydrology (e.g.; lake margins) and recently drained (within the last approx. 100 years) lake basins.'),
(4,'r','Riverine','Riverine physiography encompasses floodplains; bars; and banks along river corridors that are regularly flooded (flood return interval approx. 100 years) under the modern flow regime.'),
(5,'u','Upland','Upland physiography encompasses areas below subalpine that are flat; convex; and moderately to steeply sloping. Areas of upland physiography typically occur higher in elevation than adjacent lowlands. Soil moisture status ranges from dry to moist.');
--COMMIT;

-- insert data into the dom_geomorph table
--BEGIN;
INSERT INTO domains.dom_geomorph (sort_order, data_value, label)
VALUES
(1,'bxr','Bedrock, residual soil'),
(2,'bxw','Bedrock, weathered'),
(3,'c','Colluvial Deposit'),
(4,'ch','Hillside Colluvium'),
(5,'cs','Solifluction Deposit'),
(6,'ct','Talus'),
(7,'ctb','Talus Bluff'),
(8,'ctc','Talus Cone'),
(9,'el','Loess'),
(10,'ell','Lowland Loess'),
(11,'elu','Upland Loess'),
(12,'esda','Eolian Active Sand Dune'),
(13,'esdi','Eolian Inactive Sand Dune'),
(14,'esi','Eolian Inactive Sand Deposit'),
(15,'fboa','Braided Active Overbank Deposit'),
(16,'fbob','Braided Abandoned Overbank Deposit'),
(17,'fboi','Braided Inactive Overbank Deposit'),
(18,'fbra','Braided Active Channel Deposit'),
(19,'fbrac','Braided Coarse Active Channel Deposit'),
(20,'fbrb','Braided Abandoned Channel Deposit'),
(21,'fbrbf','Braided Fine Abandoned Channel Deposit'),
(22,'fbric','Braided Coarse Inactive Channel Deposit'),
(23,'fbrif','Braided Fine Inactive Channel Deposit'),
(24,'ffb','Alluvial Fan Abandoned Deposit'),
(25,'ffi','Alluvial Fan Inactive Deposit'),
(26,'ffric','Alluvial Fan Coarse Inactive Channel'),
(27,'ffrif','Alluvial Fan Fine-grained Inactive Channel'),
(28,'fhl','Lowland Headwater Floodplain'),
(29,'fhlo','Lowland Headwater Floodplain Overbank Deposit'),
(30,'fhm','Moderately Steep Headwater Floodplain'),
(31,'fhmc','Moderately Steep Headwater Floodplain Channel Deposit'),
(32,'fhmo','Moderately Steep Headwater Floodplain Overbank Deposit'),
(33,'fhs','Steep Stream Headwater Floodplain'),
(34,'fmoa','Meander Active Overbank Deposit'),
(35,'fmob','Meander Abandoned Overbank Deposit'),
(36,'fmoi','Meander Inactive Overbank Deposit'),
(37,'fmrac','Meander Coarse Active Channel Deposit'),
(38,'fmraf','Meander Fine Active Channel Deposit'),
(39,'fmrb','Meander Abandoned Channel Deposit'),
(40,'fmrbc','Meander Coarse Abandoned Channel Deposit'),
(41,'fmri','Meander Inactive Channel Deposit'),
(42,'fmric','Meander Coarse Inactive Channel Deposit'),
(43,'fmrif','Meander Fine Inactive Channel Deposit'),
(44,'fs','Retransported Deposit'),
(45,'fsa','Sandy Retransported Deposit'),
(46,'fsl','Lowland Retransported Deposit'),
(47,'fsu','Upland Retransported Deposit'),
(48,'fto','Old Alluvial Terrace'),
(49,'gfk','Glaciofluvial Kame Deposit'),
(50,'gl','Glaciolacustrine Deposit'),
(51,'gmo','Moraine, older'),
(52,'gmy','Moraine, younger'),
(53,'gto','Older Till'),
(54,'l','Lacustrine Deposit'),
(55,'lb','Lacustrine Beach'),
(56,'lbg','Lacustrine Beach, gravelly'),
(57,'ldic','Drained Basin, ice-rich center'),
(58,'ldim','Drained Lake Basin, ice-rich margin'),
(59,'ldnc','Drained Lake Basin, ice-poor center'),
(60,'ldnm','Drained Lake Basin, ice-poor margin'),
(61,'ltic','Thaw Basin, ice-rich center'),
(62,'ltim','Thaw Basin, ice-rich margin'),
(63,'ltiu','Thaw Basin, ice-rich undifferentiated'),
(64,'ltnm','Thaw Basin, ice-poor margin'),
(65,'ltnu','Thaw Basin, ice-poor undifferentiated'),
(66,'ns','Schist'),
(67,'ob','Bogs'),
(68,'obc','Collapse Scar Bog'),
(69,'of','Organic Fen'),
(70,'ofc','Channel Fen'),
(71,'ofsh','Shore Fen'),
(72,'sc','Sedimentary Bedrock, carbonate'),
(73,'wld','Deep Lake'),
(74,'wldcm','Deep Connected Moraine or Kettle Lake'),
(75,'wldi','Deep Isolated Lake'),
(76,'wldim','Deep Isolated Moraine or Kettle Lake'),
(77,'wldit','Deep Isolated Thaw Lake'),
(78,'wlscm','Shallow Connected Moraine or Kettle Lake'),
(79,'wlsi','Shallow Isolated Lake'),
(80,'wlsid','Shallow Isolated Dune Lake'),
(81,'wlsim','Shallow Isolated Moraine or Kettle Lake'),
(82,'wlsir','Shallow Isolated Riverine Lake'),
(83,'wlsit','Shallow Isolated Thaw Lake'),
(84,'wrhl','Lowland Headwater Stream'),
(85,'wrhm','Mountain Headwater Stream'),
(86,'wrln','Lower Perennial River, non-glacial'),
(87,'wrun','Upper Perennial River, non-glacial');
--COMMIT;

-- insert at into the dom_microtopo table 
--BEGIN;
INSERT INTO domains.dom_microtopo (sort_order, data_value, label)
VALUES
(1,'d','Drainage Or Erosion Related'),
(2,'dc','Riverbed Cobbles Or Boulders'),
(3,'dd','Flow Dunes'),
(4,'dr','Ripples'),
(5,'ds','Scour Channels-Ridges'),
(6,'dt','Water Tracks (Non-Incised Drainages)'),
(7,'e','Eolian Related'),
(8,'eb','Scour Depressions'),
(9,'es','Small Dunes'),
(10,'f','Frost Features'),
(11,'fc','Sorted Circles'),
(12,'ff','Non-Sorted Circles, Boils And Scars'),
(13,'fh','Hummocks'),
(14,'fn','Nets (Non-Sorted, Sorted)'),
(15,'fs','Stripes (Non-Sorted, Sorted)'),
(16,'ft','Steps (Non-Sorted, Sorted)'),
(17,'m','Mounds (Ice And Peat Related)'),
(18,'mg','Gelifluction Lobes'),
(19,'mi','Ice-Cored Mounds'),
(20,'ml','Tree Mounds (Downed Logs And Root Balls)'),
(21,'mpm','Peat Mounds'),
(22,'mrb','Rocks, Blockfields'),
(23,'mrm','Rocky Mounds/Outcrops'),
(24,'mrs','Soil-Covered Rocks'),
(25,'ms','Strang'),
(26,'mu','Undifferentiated Mounds'),
(27,'n','Nonpatterned'),
(28,'n/data','No Data'),
(29,'pd','Disjunct Polygon Rims'),
(30,'pf','Flat-Centered (Usually Phl)'),
(31,'phh','High-Centered, High-Relief Polygons'),
(32,'phl','High-Centered, Low-Relief Polygons'),
(33,'pllh','Low-Centered, Low-Relief, High-Density Polygons'),
(34,'plll','Low-Centered, Low-Relief, Low-Density Polygons'),
(35,'tp','Pits (Small Features)'),
(36,'w','Water');
--COMMIT;

-- insert data into the dom_soil_restrict_layer table
--BEGIN;
INSERT INTO domains.dom_soil_restrict_layer (sort_order, data_value, label, definition)
VALUES
(1,'n/data','No Data','Used to indicate the unintentional omission of data, e.g., the field team forgot to enter the data.'),
(2,'none','None','No soil restrictive layer present.'),
(3,'permafrost','Permafrost','Soil materials that remain below 0 degrees C for 2 or more years in a row.'),
(4,'unknown','Unknown','The presence of a restrictive layer uncertain because of the inability to sample to an adequate with the frost probe due to extremely rocky soils or deep standing water.');
--COMMIT;

-- insert data into the dom_veg_community table
--BEGIN;
INSERT INTO domains.dom_veg_community (sort_order, data_value, label)
VALUES
(1,'bbg','Barren'),
(2,'bpv','Partially Vegetated'),
(3,'fbcb','Closed Paper Birch'),
(4,'fbcp','Closed Balsam Poplar'),
(5,'fboa','Open Quaking Aspen Forest'),
(6,'fbob','Open Paper Birch'),
(7,'fbop','Open Balsam Poplar Forest'),
(8,'fbwb','Paper Birch Woodland'),
(9,'fmcsb','Closed Spruce-Paper Birch'),
(10,'fmosb','Open Spruce-Paper Birch'),
(11,'fmosp','Open Spruce-Balsam Poplar Forest'),
(12,'fmwsb','Spruce-Paper Birch Woodland'),
(13,'fmwsp','Spruce-Balsam Poplar Woodland'),
(14,'fnobs','Open Black Spruce Forest'),
(15,'fnows','Open White Spruce Forest'),
(16,'fnwbs','Black Spruce Woodland'),
(17,'fnwbw','Black Spruce-White Spruce Woodland'),
(18,'fnwws','White Spruce Woodland'),
(19,'haf','Aquatic Fresh Herb'),
(20,'hafb','Burreed'),
(21,'hafe','Emergent Horsetail'),
(22,'hafl','Pondlily'),
(23,'hafm','Common Marestail'),
(24,'hafp','Fresh Pondweed'),
(25,'hbbd','Dry Bryophyte'),
(26,'hbl','Lichen'),
(27,'hfds','Seral Herbs'),
(28,'hfm','Moist Forb Meadow'),
(29,'hfmm','Mixed Herbs'),
(30,'hfwhb','Subarctic Lowland Herb Bog Meadow'),
(31,'hfwhlm','Subarctic Lowland Herb Wet Meadow'),
(32,'hgdl','Elymus'),
(33,'hgmb','Bluejoint Meadow'),
(34,'hgmbh','Bluejoint-Herb'),
(35,'hgmbs','Bluejoint-Shrub'),
(36,'hgmsd','Moist Sedge-Dryas Tundra'),
(37,'hgmsgt','Moist Sedge-Grass Meadow Tundra'),
(38,'hgmss','Moist Sedge-Shrub Tundra'),
(39,'hgmswt','Moist Sedge-Willow Tundra'),
(40,'hgmt','Tussock Tundra'),
(41,'hgwfg','Fresh Grass Marsh'),
(42,'hgwfs','Fresh Sedge Marsh'),
(43,'hgwsb','Subarctic Lowland Sedge Bog Meadow'),
(44,'hgwsht','Wet Sedge-Herb Meadow Tundra'),
(45,'hgwsl','Subarctic Lowland Sedge Wet Meadow'),
(46,'hgwsmb','Subarctic Lowland Sedge-Moss Bog Meadow'),
(47,'hgwst','Wet Sedge Meadow Tundra'),
(48,'hgwswt','Wet Sedge-Willow Tundra'),
(49,'sddf','Dryas-Forb Dwarf Shrub Tundra'),
(50,'sddl','Dryas-Lichen Dwarf Shrub Tundra'),
(51,'sdds','Dryas-Sedge Dwarf Shrub Tundra'),
(52,'sddt','Dryas Dwarf Shrub Tundra'),
(53,'sdec','Cassiope Dwarf Shrub Tundra'),
(54,'sdee','Crowberry Dwarf Shrub Tundra'),
(55,'sdel','Ericaceous-Lichen Dwarf Shrub Tundra'),
(56,'sdet','Ericaceous Dwarf Shrub Tundra'),
(57,'sdev','Vaccinium Dwarf Shrub Tundra'),
(58,'sdwt','Willow Dwarf Shrub Tundra'),
(59,'sfoa','Open Dwarf Quaking Aspen'),
(60,'sfobs','Open Dwarf Black Spruce'),
(61,'sfop','Open Dwarf Balsam Poplar'),
(62,'sfows','Open Dwarf White Spruce'),
(63,'sfwws','Dwarf White Spruce Woodland'),
(64,'slcb','Closed Low Shrub Birch'),
(65,'slcbe','Closed Low Shrub Birch-Ericaceous Shrub'),
(66,'slcbw','Closed Low Shrub Birch-Willow'),
(67,'slcw','Closed Low Willow'),
(68,'slo','Open Low Shrub'),
(69,'sloa','Open Low Alder'),
(70,'sloaw','Open Low Alder-Willow'),
(71,'slobb','Open Low Shrub Birch-Ericaceous Shrub Bog'),
(72,'slobe','Open Low Mesic Shrub Birch-Ericaceous Shrub'),
(73,'slobw','Open Low Shrub Birch-Willow'),
(74,'slocg','Open Low Sweetgale-Graminoid Shrub Bog'),
(75,'slod','Open Low Scrub, post burn or disturbance'),
(76,'sloe','Open Low Ericaceous Shrub'),
(77,'sloeb','Open Low Ericaceous Shrub Bog'),
(78,'slosg','Open Sagebrush-Grass'),
(79,'slotb','Open Mixed Low Shrub-Sedge Tussock Bog Meadow'),
(80,'slott','Open Mixed Low Shrub-Sedge Tussock Tundra'),
(81,'slow','Open Low Willow'),
(82,'slows','Open Low Willow-Sedge Shrub Tundra'),
(83,'stca','Closed Tall Alder'),
(84,'stcaw','Closed Tall Alder-Willow'),
(85,'stcb','Closed Tall Shrub Birch'),
(86,'stcbw','Closed Tall Shrub Birch-Willow'),
(87,'stcw','Closed Tall Willow'),
(88,'stoa','Open Tall Alder'),
(89,'stoaw','Open Tall Alder-Willow'),
(90,'stobw','Open Tall Shrub Birch-Willow'),
(91,'stod','Open Tall Scrub, post burn or disturbance'),
(92,'stow','Open Tall Willow'),
(93,'wf','Fresh Water');
COMMIT;